### PR TITLE
feat: allow import of newer pocket data export files in csv format

### PR DESCRIPTION
**Pull request by melnary**
Recently Pocket changed the format of their data export function, switching from HTML files to a zipped folder containing CSV files, delivered in parts of up to 10000 bookmarks.
Other bookmark managers were also affected by this, as seen here: https://github.com/hoarder-app/hoarder/issues/570

This patch allows the `pocket` sub-command to handle these files correctly, expanding it's functionality to import both HTML and CSV files, as I believe the ability to import older exports may still be useful. This is done by a simple file extension check, which I think will suffice for most users.

Note that the command still does not process the multiple part files explicitly, so the user has to import them one by one, which I don't think will be too much of a hassle for the user either way. :)

I would appreciate it if someone could test this patch on an older HTML file (or give me one so I could test it myself :3), as I was only able to test it with my own CSV export.

### CODE REVIEW

**Comment by fmartingr** [comment]
Hey @melnary, thanks for the contribution! I'm not super famiiar with pocket and their exports so for me if you tested it it's good to go. Can you take a look at the CI errors and correct them though?

**Comment by melnary** [comment]
@fmartingr Hi! I was wondering where the CI was at :3
Do we have something to address coverage in the cmd package?

**Comment by fmartingr** [comment]
Dont worry about coverage, the linter errors are here: https://github.com/go-shiori/shiori/actions/runs/12276136781/job/34257042686#step:3:1

**Comment by melnary** [comment]
@fmartingr Please approve the workflows again, my local linter is reporting no errors, should be good to go!

**Comment by melnary** [comment]
Ah and one more thing! I did manage to track down an [older HTML export file](https://github.com/mufidu/pocket-to-markdown/blob/master/ril_export.html), to make sure that I didn't end up breaking the HTML import feature, luckily it all still works smoothly!

**Comment by fmartingr** [comment]
> Ah and one more thing! I did manage to track down an [older HTML export file](https://github.com/mufidu/pocket-to-markdown/blob/master/ril_export.html), to make sure that I didn't end up breaking the HTML import feature, luckily it all still works smoothly!

That's awesome!

**Review by fmartingr — APPROVED** [review]
Thank you for the contribution!

**Comment by Panphico** [comment]
Hi, thank you all for the patch. However, this patch use a mandatory "cursor" field (Invalid CSV format. Header must be: title,url,time_added,cursor,tags,status) that is not in my pocket extract. Could you make this field optional please ?

**Pull request merged**
