### PR TITLE
fix: use noreferer to prevent exposing shiori instance url to archived websites

### PR DESCRIPTION
**Pull request by istiak101**
https://caniuse.com/rel-noreferrer

### CODE REVIEW

**Comment by Monirzadeh** [comment]
should we do that in this line too?
https://github.com/go-shiori/shiori/blob/188ce68761eada733d2fc905df71ca3f68de4058/internal/view/content.html#L29

**Comment by istiak101** [comment]
> should we do that in this line too?

I haven't found its usage yet in the application. If it goes to a url in browser then yes. Can you please confirm?

**Comment by Monirzadeh** [comment]
as i see you add `noreferrer` for link to the bookmark link in home page. right?
we have other link too. for example in content page:
https://github.com/go-shiori/shiori/blob/188ce68761eada733d2fc905df71ca3f68de4058/internal/view/content.html#L29-L36
or
https://github.com/go-shiori/shiori/blob/188ce68761eada733d2fc905df71ca3f68de4058/internal/webserver/handler.go#L74-L84

why you not add `noreferrer` to them?

**Comment by istiak101** [comment]
I downloaded the stable release which is 49 commits behind. I will build main and check again.

**Comment by fmartingr** [comment]
As @Monirzadeh pointed out, there are other places where we link to the original bookmark URL, but in general I think this is a good addition. Ping me if you need help pinpointing where all the links are in the code and thank you for the contribution!

**Comment by istiak101** [comment]
Thanks @Monirzadeh for pointing out missing noreferrer value.

@fmartingr I have updated the PR. I think these are only places where noreferrer is required.

**Review by fmartingr — APPROVED** [review]
I think you covered all links with this, thanks for your contribution!

**Comment by fmartingr** [comment]
> LGTM 👍 Thanks for PR we can open an issue for
> 
> > Edit: bookmark/ID/content and bookmark/ID/archive/ would still leak shiori servers url. I am not familiar with the project but I think this is done with https://github.com/go-shiori/dom .

I think he solved most of the links around. Since we need to work a bit on archives in the future I'd say this is a non-issue for us until we get a contributor to handle this.

**Pull request merged**
