### PR TITLE
feat: allow authentication using proxy request header

### PR DESCRIPTION
**Pull request by PterX**
This submission implements the working method of oauth header authentication, which needs to be combined with the reverse proxy service and oauth service to achieve password-free authentication login.
For example: The following is explained by combining the configuration of nginx and authelia
Refer to the auth documentation page https://www.authelia.com/integration/proxies/nginx/

We can use the following configurations
/config/nginx/snippets/proxy.conf
/config/nginx/snippets/authelia-location.conf
/config/nginx/snippets/authelia-authrequest.conf

nginx configuration is as follows
```
server{
    listen 80;
    server_name shiori.example.com;

    include /config/nginx/snippets/authelia-location.conf;

    location / {
        proxy_pass http://10.0.0.1:8080; // pass to shiori
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        include /config/nginx/snippets/authelia-authrequest.conf;
        include /config/nginx/snippets/proxy.conf;
    }
}
```

Way of working
step 1
Client  request -> nginx proxy(auth request, not login) -> authelia ( redirect to auth page)  

step 2
Client  request -> nginx proxy(auth request, it was login with oauth) -> authelia (verify api) -> shiori (get auth user header, like user name) -> shiori (getTokenFromAuthHeader:  trust && query account by user name) -> shiori (generate token and session-id,save to cookie)

step 2
Client request(with token,session-id) -> nginx proxy(also auth request,ignore) -> shiori (old work path, getTokenFromCookie, and other check ...) -> shiori (user verify ok) -> shiori ( business code)

Closes #594

### CODE REVIEW

**Comment by fmartingr** [comment]
Hey @PterX, thanks for the PR and taking care of moving this forward.

Can you put out a description to the PR for future reference and a way for us reviewers to test it? Consider that some may be unfamiliar with these authentication methods or lack the experience to properly test this locally. I would also love to know more about the standard behind this auth operation, to see if this logic would match many (or all) providers or we are targeting a specific one.

Code review will be performed during the week, I want to finish and release 1.6.0 first.

**Comment by PterX** [comment]
> Hey @PterX, thanks for the PR and taking care of moving this forward.
> 
> Can you put out a description to the PR for future reference and a way for us reviewers to test it? Consider that some may be unfamiliar with these authentication methods or lack the experience to properly test this locally. I would also love to know more about the standard behind this auth operation, to see if this logic would match many (or all) providers or we are targeting a specific one.
> 
> Code review will be performed during the week, I want to finish and release 1.6.0 first.

I was update the description to the PR, please check it again

**Comment by PterX** [comment]
it look like lose this pull request, ^.^

**Comment by fmartingr** [comment]
> it look like lose this pull request, ^.^

What exactly happened here? I did not merge your changes upstream and the PR shows no changes. Can you manually update your branch from latest master to see if we can recover the PR? 🤔

**Pull request merged**
