### PR TITLE
Even more efficient, using ADD instead of copy

### PR DESCRIPTION
**Pull request by symgryph**
This speeds up rebuild times, since ADD doesn't invalidate cache. Also incoporates 3 other pull requests.

### CODE REVIEW

**Comment by symgryph** [comment]
my last 3 pull requests

**Comment by symgryph** [comment]
my last 3 pull requests

**Comment by symgryph** [comment]
basically these make things smaller and more secure

**Comment by deanishe** [comment]
> my last 3 pull requests

I only see two others.

**Comment by symgryph** [comment]
Whatever it’s a summation of all the previous ones

Thomas J Munn

**Comment by symgryph** [comment]
If you need someone to help with pulls for dockrr I am willing to help.

**Comment by deanishe** [comment]
> If you need someone to help with pulls for dockrr I am willing to help

Thanks, no. But if you could fix the conflicts and then squash the commits, that'd be great. Then I'll merge the PR.

**Comment by symgryph** [comment]
Too much trouble to submit

**Pull request closed without merging**
