### PR TITLE
replace http route with go-chi

### PR DESCRIPTION
**Pull request by hulb**
I prefer go-chi as a light route because I think it's more idiomatic and makes the code more understandable

### CODE REVIEW

**Comment by hulb** [comment]
I'm also hesitating about whether using [go-gin](https://github.com/gin-gonic/gin) is a better choice.

**Comment by fmartingr** [comment]
I'm going to leave this on hold, since a refactor of the API has to be made but I'd rather go in parallel to the current one. I was about to go with [fiber](https://gofiber.io/) since [I already used it and have some experience and QoL with it](https://github.dev/fmartingr/notion2ical/tree/latest/internal/server/http/server.go), but the engine doesn't matter much to me. Any comments towards gin or other http engines?

**Comment by hulb** [comment]
No,using an engine will make me to have to understand the rules of the engine.I can try fiber later.

**Comment by fmartingr** [comment]
I had the same opinion until I saw how much boilerplate I had to avoid coding 😅 You just need to figure out how to properly organize the code, the rest should be easy. Please take a look at #497. I will open a discussion so we can comment on this.

**Comment by fmartingr** [comment]
Discussion here: https://github.com/go-shiori/shiori/discussions/498

**Comment by hulb** [comment]
I have reviewed #497 , it's a big step to next.I think this PR is unneccesary and just close it.

**Pull request closed without merging**
