### PR TITLE
Draft: Replace WARC with Obelisk

### LINKED ISSUE #353: Support Obelisk archiving
It seems that shiori depends on [warc](https://github.com/go-shiori/warc) which is currently archived. We need to find a replacement for warc. Maybe [obelisk](https://github.com/go-shiori/obelisk)?

## Acceptance criteria
- Add a migration that will define in which archiver type the content is (put `warc` for already existing rows, but `obelisk` as default)
- Add logic to allow multiple archivers to be used, **do not** remove Warc logic, just refactor it.
- Allow the `/bookmark/:id/archive` handler to load multiple archive types (to load old and new)
- Allow the `POST /api/v1/bookmarks`/`POST /api/v1/bookmarks/cache`/`POST /api/v1/bookmarks/:id/cache` to select which archiver to use (but hardcode/default it to `obelisk`).
- Add a documentation page describing the archivers, available options, pro-cons.
- Determine if different extensions should be used from now on (leave current filename expectations **intact**)
- All code logic should be properly tested
- Swagger documentation should be updated

### PR DESCRIPTION
**Pull request by fmartingr**
This is a draft to replace WARC with Obelisk in order to know what would be the impact of such a change.

Notes:
- Serving content (not archives) uses the archive in some way. Don't know why, need to investigate
- Old archives would require a migration from the old system (WARC) to the new one (Obelisk) potentially saving up space and being much more confortable to manage since it will create single files.
- Right now storage is file-based, I would move things to database with a cache layer so its easier for us to manage and for users to backup, manage and migrate.

Closes #353

### CODE REVIEW

**Comment by Katarn** [comment]
> Right now storage is file-based, I would move things to database with a cache layer so its easier for us to manage and for users to backup, manage and migrate.

I would make this functionality optional. I'm afraid to imagine how large the database dumps will be, they are clearly not intended for such use.

**Comment by hulb** [comment]
Actually I have a need for shiori to save these archive files to object storage like minio :)

**Comment by fmartingr** [comment]
> Actually I have a need for shiori to save these archive files to object storage like minio :)

I believe you already can mount volumes as s3-compatible storage by using docker/k8s?

**Comment by fmartingr** [comment]
This was very outdated and it has very fee work on it. The PDF archiver refactored most of the logic so I need to start over when that PR is merged.

**Pull request closed without merging**
